name: Deploy

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, apolo]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ~/f1-bot

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Cria .env
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
        working-directory: ~/f1-bot

      - name: Instala dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: ~/f1-bot