name: Deploy

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, apolo-runner]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build f1bot docker image
        run: |
          docker compose -f docker/docker-compose.yml build --no-cache

  deploy:
    runs-on: [self-hosted, apolo-runner]
    needs: build
    steps:
      - name: Deploy f1bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          docker compose -f docker/docker-compose.yml up -d --remove-orphans
