name: Deploy

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, apolo-runner]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build f1bot docker image
        run: |
          docker-compose -f docker/docker-compose.yml build --no-cache

  deploy:
    runs-on: [self-hosted, apolo-runner]
    needs: build
    steps:
      - name: create .env
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

      - name: Deploy f1bot
        run: |
          docker-compose -f docker/docker-compose.yml down
          docker-compose -f docker/docker-compose.yml --env-file .env up -d