name: Deploy

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, apolo-runner]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Cria .env
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env

      - name: Instala dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt